<?php
/**
 * Sticky TOC Component
 *
 * Note: This file can be included directly if needed,
 * but the TOC is typically generated by CT_Docs_TOC_Generator
 * and output in single-docs.php
 *
 * @package CT_Docs
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

$post_id = get_the_ID();
$toc_html = CT_Docs_TOC_Generator::get_toc( $post_id );

if ( ! empty( $toc_html ) ) {
    echo '<div class="ct-docs-toc-sticky">';
    echo $toc_html;
    echo '</div>';
}

